ekf_filter_node:
  ros__parameters:
    frequency: 30
    sensor_timeout: 0.1
    two_d_mode: true

    # Frame names
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # Input IMU data
    imu0: /imu
    imu0_config: [false, false, false, true, true, true, false, false, false, true, true, true]
    imu0_differential: false
    imu0_relative: true
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true

    # Input odometry data
    odom0: /odom
    odom0_config: [true, true, false, false, false, false, true, true, false, false, false, false]
    odom0_differential: false
    odom0_relative: true
    odom0_queue_size: 10

    # Output TF
    publish_tf: true
    print_diagnostics: true

